# Generated by Django 5.2.7 on 2025-10-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='default_username', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'phone_number')},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profiles',
        ),
    ]
