# Generated by Django 5.2.7 on 2025-10-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_profile_isactive_profile_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forget_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_Bloked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
    ]
