# Generated by Django 5.2.7 on 2025-10-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_profile_forget_password_profile_is_bloked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verification_code',
        ),
    ]
