# Generated by Django 5.2.7 on 2025-11-03 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_profile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('security_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('push_notifications', models.BooleanField(default=False)),
                ('account_updates', models.BooleanField(default=False)),
                ('online_status', models.BooleanField(default=False)),
                ('privacy_mode', models.BooleanField(default=False)),
                ('language', models.CharField(default='English', max_length=50)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=50)),
                ('theme', models.CharField(default='light', max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='auth_app.profile')),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
                'db_table': 'user_settings',
            },
        ),
    ]
