from .product_view import ProductView
from .product_mixing_view import product_mixin_view
from .product_create import product_create_view ,product_details_view,product_List_view,product_update_view,product_delete_view